/**
 * @file app shell mutation types
 * @author wulei123(1534563365@qq.com)
 */

export const ENABLE_PAGE_TRANSITION = 'ENABLE_PAGE_TRANSITION';
export const DISABLE_PAGE_TRANSITION = 'DISABLE_PAGE_TRANSITION';
export const SET_PAGE_SWITCHING = 'SET_PAGE_SWITCHING';
export const SET_PAGE_TRANSITION_NAME = 'SET_PAGE_TRANSITION_NAME';
export const SET_APP_HEADER = 'SET_APP_HEADER';
export const SET_APP_BOTTOM_NAV = 'SET_APP_BOTTOM_NAV';
export const ACTIVATE_APP_BOTTOM_NAV = 'ACTIVATE_APP_BOTTOM_NAV';
export const SET_SIDEBAR_VISIBILITY = 'SET_SIDEBAR_VISIBILITY';
export const SAVE_SCROLLTOP = 'SAVE_SCROLLTOP';
export const SET_FULL_SCHEDULE = 'SET_FULL_SCHEDULE';
export const SET_FULL_SCORES = 'SET_FULL_SCORES';
export const SET_FULL_CLASSROOM = 'SET_FULL_CLASSROOM'
export const SET_ACTIVE_WEEK = 'SET_ACTIVE_WEEK'
export const SET_SELECTED = 'SET_SELECTED'
export const SET_SCORES_ACTIVE_SEMESTER = 'SET_SCORES_ACTIVE_SEMESTER'
export const SET_SELECTOR_ITEMS = 'SET_SELECTOR_ITEMS'
export const SET_SELECT_DIALOG_ACTION = 'SET_SELECT_DIALOG_ACTION'
export const SET_IS_AUTHED = 'SET_IS_AUTHED'